<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Version>0.3.5-alpha.107</Version>
    <NoWarn>NU1507</NoWarn>
    <GhulCompiler>dotnet ghul-compiler</GhulCompiler>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ghul.runtime" />

    <GhulOptions Include="--warn-as-error null-deref" />
  </ItemGroup>
</Project>